import os

ENABLE_UI_THEME_ADMINISTRATION = True

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "EMBEDDED_SUPERSET": True,
}

ENABLE_PROXY_FIX = True

SECRET_KEY = os.environ.get("SECRET_KEY")

SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE")

HTTP_HEADERS = {"X-Frame-Options": "ALLOWALL"}

WTF_CSRF_ENABLED = False

TALISMAN_ENABLED = False

PUBLIC_ROLE_LIKE = "Gamma"